name: Validate vBase public documentation Website

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON" # At 12:00 AM, only on Monday

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Run linkcheck
        run: |
          docker run --rm \
            tennox/linkcheck@sha256:e6e26d9278293c717fca4faae101dfe3c392c5b768bc06d16305ec56a7c8de5a \
            https://docs.vbase.com/
