name: Validate vBase Website

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON" # At 12:00 AM, only on Monday

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Pull linkcheck Docker image
        run: docker pull tennox/linkcheck

      - name: Run linkcheck
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/.github:/skipfiles" \
            tennox/linkcheck https://www.vbase.com/ \
            --skip-file /skipfiles/linkcheck-skip-vbase.txt
